# note setting yarnPath as yarn 3 is provided by nix shell

packageExtensions:
  "@trufflesuite/eth-json-rpc-filters@*":
    # Used in module code while only declared in dev deps
    dependencies:
      pify: ^3.0.0
